version: '3.8'
services:
  oracle-db:
    image: 'gvenzl/oracle-free:latest'
    environment:
      - APP_USER=coop_vote
      - APP_USER_PASSWORD=oracle2026
      - ORACLE_PASSWORD=oracle2026
    ports:
      - "1521:1521"
    volumes:
      - oracle-db-data:/u01/app/oracle/oradata
    networks:
      - app-network

volumes:
  oracle-db-data:

networks:
  app-network:
    driver: bridge